// Seed data for the e-commerce store
import { seedDatabase } from './mock-db';
import type { Product } from './types';

const seedProducts: Omit<Product, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'ReLuma Intensive Serum',
    description: 'Our flagship intensive serum combines powerful growth factors with peptides to dramatically improve skin firmness, texture, and radiance. Clinically proven to reduce fine lines and wrinkles in just 4 weeks.',
    price: 149.99,
    compareAtPrice: 199.99,
    category: 'Serums',
    images: [
      '/assets/option1/desktop/product-serum-1.jpg',
      '/assets/option1/desktop/product-serum-2.jpg',
      '/assets/option1/desktop/product-serum-3.jpg',
    ],
    inventoryQuantity: 50,
    lowStockThreshold: 10,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 0,
    sku: 'RL-SRM-001',
    tags: ['bestseller', 'anti-aging', 'serum', 'growth-factors'],
  },
  {
    name: 'ReLuma Daily Moisturizer',
    description: 'Lightweight yet deeply hydrating moisturizer formulated with hyaluronic acid and ceramides. Locks in moisture for 24-hour hydration while supporting skin barrier function.',
    price: 89.99,
    compareAtPrice: 119.99,
    category: 'Moisturizers',
    images: [
      '/assets/option1/desktop/product-moisturizer-1.jpg',
      '/assets/option1/desktop/product-moisturizer-2.jpg',
    ],
    inventoryQuantity: 75,
    lowStockThreshold: 15,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 0,
    sku: 'RL-MST-001',
    tags: ['daily-care', 'hydration', 'moisturizer'],
  },
  {
    name: 'ReLuma Eye Renewal Cream',
    description: 'Targeted eye treatment that reduces dark circles, puffiness, and crow\'s feet. Gentle yet effective formula safe for the delicate eye area.',
    price: 79.99,
    category: 'Eye Care',
    images: [
      '/assets/option1/desktop/product-eye-cream-1.jpg',
      '/assets/option1/desktop/product-eye-cream-2.jpg',
    ],
    inventoryQuantity: 30,
    lowStockThreshold: 10,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 0,
    sku: 'RL-EYE-001',
    tags: ['eye-care', 'anti-aging', 'dark-circles'],
  },
  {
    name: 'ReLuma Exfoliating Cleanser',
    description: 'Gentle daily cleanser with natural exfoliants that remove dead skin cells without stripping natural oils. Leaves skin feeling fresh, smooth, and radiant.',
    price: 49.99,
    category: 'Cleansers',
    images: [
      '/assets/option1/desktop/product-cleanser-1.jpg',
    ],
    inventoryQuantity: 100,
    lowStockThreshold: 20,
    isActive: true,
    averageRating: 4.5,
    reviewCount: 0,
    sku: 'RL-CLN-001',
    tags: ['cleansing', 'exfoliating', 'daily-care'],
  },
  {
    name: 'ReLuma Night Repair Complex',
    description: 'Intensive overnight treatment that works while you sleep to repair and regenerate skin. Wake up to visibly smoother, more youthful-looking skin.',
    price: 129.99,
    compareAtPrice: 159.99,
    category: 'Night Care',
    images: [
      '/assets/option1/desktop/product-night-1.jpg',
      '/assets/option1/desktop/product-night-2.jpg',
    ],
    inventoryQuantity: 8,
    lowStockThreshold: 10,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 0,
    sku: 'RL-NGT-001',
    tags: ['night-care', 'anti-aging', 'repair', 'bestseller'],
  },
  {
    name: 'ReLuma Vitamin C Brightening Serum',
    description: 'Potent vitamin C formula that brightens dull skin, fades dark spots, and evens skin tone. Antioxidant-rich to protect against environmental damage.',
    price: 99.99,
    category: 'Serums',
    images: [
      '/assets/option1/desktop/product-vitamin-c-1.jpg',
    ],
    inventoryQuantity: 45,
    lowStockThreshold: 10,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 0,
    sku: 'RL-SRM-002',
    tags: ['brightening', 'vitamin-c', 'serum', 'antioxidant'],
  },
  {
    name: 'ReLuma SPF 50 Daily Defense',
    description: 'Broad-spectrum sunscreen that protects against UVA/UVB rays while providing anti-aging benefits. Lightweight, non-greasy formula perfect for daily use.',
    price: 59.99,
    category: 'Sun Protection',
    images: [
      '/assets/option1/desktop/product-spf-1.jpg',
    ],
    inventoryQuantity: 60,
    lowStockThreshold: 15,
    isActive: true,
    averageRating: 4.4,
    reviewCount: 0,
    sku: 'RL-SUN-001',
    tags: ['sunscreen', 'spf', 'daily-care', 'protection'],
  },
  {
    name: 'ReLuma Complete Skincare Set',
    description: 'Our complete 5-piece skincare routine includes cleanser, serum, moisturizer, eye cream, and SPF. Everything you need for radiant, youthful skin. Save 20% versus buying separately.',
    price: 399.99,
    compareAtPrice: 499.99,
    category: 'Sets',
    images: [
      '/assets/option1/desktop/product-set-1.jpg',
      '/assets/option1/desktop/product-set-2.jpg',
    ],
    inventoryQuantity: 25,
    lowStockThreshold: 5,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 0,
    sku: 'RL-SET-001',
    tags: ['set', 'bundle', 'bestseller', 'value'],
  },
];

// Initialize the database with seed data
export function initializeDatabase() {
  seedDatabase(seedProducts);
}
